### ISSUE TITLE
How can change splash background?

### ISSUE THREAD

**Issue by MohMehrnia** [MehdiKhoshnevisz/vue-splash#2]
How can change splash background?

**Comment by MehdiKhoshnevisz** [comment]
I added this feature in this [release](https://github.com/MehdiKhoshnevisz/vue-splash/releases/tag/1.2.0).
You can set the `background-color` property to any hex colors that you want.

**Comment by MohMehrnia** [comment]
can set a background image?

**Comment by MehdiKhoshnevisz** [comment]
no!

**Comment by MehdiKhoshnevisz** [comment]
but in the future...
